// Writes docs/STATS.md from the repository itself: seeded data, code size,
// commit history and the agent logs. Re-run any time: `npm run stats`.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = process.cwd();
const read = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const fmt = (n) => Math.round(n).toLocaleString('en-US');
const hm = (s) => `${Math.floor(s / 3600)}h ${String(Math.round((s % 3600) / 60)).padStart(2, '0')}m`;
const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.round(s % 60)).padStart(2, '0')}`;
const short = (s, n = 56) => (s.length <= n ? s : s.slice(0, s.lastIndexOf(' ', n)) + '…');
const clean = (s) => s.replace(/[:;#"]/g, ' ').replace(/\s+/g, ' ').trim();

// ---------- seeded data ----------
const index = read('src/data/generated/index.json');
const people = read('src/data/generated/people.json');
const meetings = index.map((m) => read(`src/data/generated/meetings/${m.id}.json`));
const words = (m) => m.turns.reduce((a, t) => a + t.t.split(/\s+/).length, 0);
const sum = (f) => meetings.reduce((a, m) => a + f(m), 0);
const data = {
  meetings: meetings.length,
  people: people.length,
  turns: sum((m) => m.turns.length),
  words: sum(words),
  seconds: sum((m) => m.duration),
  actions: sum((m) => m.actionItems.length),
  highlights: sum((m) => m.highlights.length),
  chapters: sum((m) => m.chapters.length),
  summaries: sum((m) => Object.keys(m.summaries).length),
  ask: sum((m) => m.ask.length),
  external: meetings.filter((m) => m.kind === 'external').length,
};
const q4 = meetings.find((m) => m.id === 'q4-planning') ?? meetings[0];
const name = (id) => people.find((p) => p.id === id)?.name ?? id;

// ---------- code ----------
const walk = (dir) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => (d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]))
    : [];
const lines = (f) => fs.readFileSync(f, 'utf8').split('\n').length;
const AREAS = [
  ['Meeting page', 'src/components/meeting'],
  ['Landing page', 'src/components/landing'],
  ['Other components', 'src/components', (f) => !/[\\/](meeting|landing)[\\/]/.test(f)],
  ['Routes (src/app)', 'src/app'],
  ['Logic (src/lib)', 'src/lib'],
  ['Data scripts', 'scripts'],
  ['Capture hook', '.claude/hooks', (f) => !f.includes('.state')],
];
const code = AREAS.map(([label, dir, keep = () => true]) => {
  const files = walk(path.join(ROOT, dir)).filter((f) => /\.(tsx?|mjs|css)$/.test(f) && keep(f));
  return { label, dir, files: files.length, lines: files.reduce((a, f) => a + lines(f), 0) };
});
const codeTotal = code.reduce((a, c) => ({ files: a.files + c.files, lines: a.lines + c.lines }), { files: 0, lines: 0 });
const authored = walk(path.join(ROOT, 'data/source'));
const authoredBytes = authored.reduce((a, f) => a + fs.statSync(f).size, 0);
const pkg = read('package.json');
const routes = walk(path.join(ROOT, 'src/app')).filter((f) => /page\.tsx$/.test(f)).length;
const components = walk(path.join(ROOT, 'src/components')).filter((f) => f.endsWith('.tsx')).length;

// ---------- history ----------
const git = (...args) => {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
};
const commits = git('log', '--reverse', '--format=%ad|%s', '--date=format:%Y-%m-%d_%H:%M')
  .split('\n')
  .filter(Boolean)
  .map((l) => {
    const [when, ...msg] = l.split('|');
    return { when: when.replace('_', ' '), msg: msg.join('|') };
  });

// ---------- agent logs ----------
const logDir = path.join(ROOT, '.agent-logs');
const logs = fs.existsSync(logDir) ? fs.readdirSync(logDir).filter((f) => f.endsWith('.md')) : [];
const logStats = logs.map((f) => {
  const s = fs.readFileSync(path.join(logDir, f), 'utf8');
  return { f, prompts: (s.match(/type=PROMPT/g) || []).length, responses: (s.match(/type=RESPONSE/g) || []).length, kb: Math.round(Buffer.byteLength(s) / 1024) };
});
const skills = fs.existsSync(path.join(ROOT, '.claude/skills')) ? fs.readdirSync(path.join(ROOT, '.claude/skills')) : [];

// ---------- build ----------
const outDir = path.join(ROOT, 'out');
const outFiles = walk(outDir);
const outMB = outFiles.reduce((a, f) => a + fs.statSync(f).size, 0) / 1048576;
const htmlPages = outFiles.filter((f) => f.endsWith('.html')).length;

// ---------- write ----------
const md = [];
md.push('# Project stats', '');
md.push(`Generated by \`npm run stats\` ([scripts/doc-stats.mjs](../scripts/doc-stats.mjs)) from the repository itself. Last run: ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC.`, '');

md.push('## At a glance', '');
md.push('| | |', '|---|---|');
md.push(`| Seeded meetings | ${data.meetings} (${data.external} with customers, ${data.meetings - data.external} internal) |`);
md.push(`| People in the seeded company and its customers | ${data.people} |`);
md.push(`| Talk time | ${hm(data.seconds)} |`);
md.push(`| Words of transcript | ${fmt(data.words)} |`);
md.push(`| Turns (a stretch of one person speaking) | ${fmt(data.turns)} |`);
md.push(`| Action items | ${data.actions} |`);
md.push(`| Seeded clips | ${data.highlights} |`);
md.push(`| Chapters | ${data.chapters} |`);
md.push(`| Note summaries (meeting × template) | ${data.summaries} |`);
md.push(`| Prepared Ask answers | ${data.ask} |`);
md.push(`| Pages (routes) | ${routes} route files, ${htmlPages || 'n/a'} HTML pages in the static build |`);
md.push(`| React components | ${components} |`);
md.push(`| Hand-written code | ${fmt(codeTotal.lines)} lines in ${codeTotal.files} files |`);
md.push(`| Authored source data | ${authored.length} files, ${fmt(authoredBytes / 1024)} KB |`);
md.push(`| Runtime dependencies | ${Object.keys(pkg.dependencies).length} (${Object.keys(pkg.dependencies).join(', ')}) |`);
md.push(`| Commits | ${commits.length} |`);
md.push(`| Agent log sessions | ${logs.length}, with ${logStats.reduce((a, l) => a + l.prompts, 0)} prompts logged |`);
if (outFiles.length) md.push(`| Static build size | ${outMB.toFixed(1)} MB |`);
md.push('');

md.push('## The meetings', '');
md.push('| Meeting | Type | People | Length | Turns | Words | Action items | Chapters |', '|---|---|---:|---:|---:|---:|---:|---:|');
for (const m of meetings) {
  md.push(`| [${m.title}](https://ashboi-cyber.github.io/fathom-rebuild/meetings/${m.id}/) | ${m.type} | ${m.participants.length} | ${mmss(m.duration)} | ${m.turns.length} | ${fmt(words(m))} | ${m.actionItems.length} | ${m.chapters.length} |`);
}
md.push('');

md.push('### Minutes of talk per meeting', '');
md.push('```mermaid', 'pie showData', '  title Minutes of talk per meeting');
for (const m of meetings) md.push(`  "${clean(m.title.split(':')[0])}" : ${Math.round(m.duration / 60)}`);
md.push('```', '');

md.push(`### Who talked in the 8-person call (${clean(q4.title)})`, '');
md.push('The case the brief singles out. Share of talk time, in minutes:', '');
md.push('```mermaid', 'pie showData', '  title Talk time, Q4 planning (minutes)');
for (const [id, s] of Object.entries(q4.talk).sort((a, b) => b[1] - a[1])) md.push(`  "${name(id)}" : ${(s / 60).toFixed(1)}`);
md.push('```', '');

md.push('## The code', '');
md.push('| Area | Folder | Files | Lines |', '|---|---|---:|---:|');
for (const c of code) md.push(`| ${c.label} | \`${c.dir}\` | ${c.files} | ${fmt(c.lines)} |`);
md.push(`| **Total** | | **${codeTotal.files}** | **${fmt(codeTotal.lines)}** |`, '');
md.push('```mermaid', 'pie showData', '  title Lines of code by area');
for (const c of code) md.push(`  "${c.label}" : ${c.lines}`);
md.push('```', '');

md.push('## How the build went', '');
md.push('Every commit, in order (local time). The gaps between them are the work.', '');
md.push('```mermaid', 'gantt', '  title Commit timeline', '  dateFormat YYYY-MM-DD HH:mm', '  axisFormat %H:%M', '  section Commits');
commits.forEach((c, i) => {
  const start = i ? commits[i - 1].when : c.when;
  md.push(`  ${short(clean(c.msg))} :${start === c.when ? 'milestone, ' : ''}${start}, ${start === c.when ? '0m' : c.when}`);
});
md.push('```', '');
md.push('| When | Commit |', '|---|---|');
for (const c of commits) md.push(`| ${c.when} | ${c.msg} |`);
md.push('');

md.push('## Agent logs', '');
md.push('Captured automatically by the hook in `.claude/hooks/capture.mjs` (see [CAPTURE-TEST.md](../CAPTURE-TEST.md)). Never edited by hand.', '');
md.push('| Log file | Prompts | Responses | Size |', '|---|---:|---:|---:|');
for (const l of logStats) md.push(`| [${l.f}](../.agent-logs/${l.f}) | ${l.prompts} | ${l.responses} | ${l.kb} KB |`);
md.push('');
md.push(`Project skills installed in \`.claude/skills\`: ${skills.map((s) => `\`${s}\``).join(', ')}. GSAP's official skills were installed at user level.`, '');

fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'docs/STATS.md'), md.join('\n'));
console.log(`docs/STATS.md: ${data.meetings} meetings, ${fmt(codeTotal.lines)} lines of code, ${commits.length} commits`);
